#!/usr/bin/env python
# coding: utf-8

import os
import os.path
import pandas as pd
import glob

#     This function removes duplicate and NaN entries for the weather *.tabs generated by API Weather.py
#     First need to add dirty files to the folder in DIRECTORY

# ================================================================================================
#     Only edit these two variables
DIRECTORY = "D:/James/Documents/Python Scripts/Duplicate_NaN_Fix/"
OUTPUT = "D:/James/Documents/Python Scripts/Duplicate_NaN_Fix/Fixed/"
# ================================================================================================

TAB_EXTENSION = ".tab"

def load_dfs(directory):

#     Create an empty dictionary to fill with filenames and dfs
#     key is the file name, value is the df

    DfDic = {}

    for file in glob.glob(directory + "\\*.tab"):
        filename = os.path.basename(file)
#         file gives the 'absolute path' inclusive of filename AND directory
#         Only gives the filename without directory
        DfDic[filename] = pd.read_csv(file, sep='\t')

    return DfDic

files = load_dfs(DIRECTORY)

for FileName, DF in files.items():

#     iterating through a dictionary of pandas.values DF instead of one pandas df at a time
#     key is the file name, value is the df

    NoDupdf = DF.drop_duplicates(subset = ["UNIX_UTC","Temp","Wind_speed[m/s]"], keep="first")
    NoNAN = NoDupdf.dropna()
    CityStr = (FileName.split('.'))
    file_save = OUTPUT+CityStr[0]+TAB_EXTENSION
    NoNAN.to_csv(file_save, sep='\t', mode='w', index=False)

